name: Main CI
on:
  push:
    branches:
      - main
env:
  CI: true
  GITHUB_BRANCH: ${{ github.ref }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}
  GITHUB_BASE_REF: ${{ github.base_ref }}
  GITHUB_COMMIT: ${{ github.sha }}
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ '17' ]
      fail-fast: false
    name: ${{ matrix.os }} JDK ${{ matrix.java }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: ${{ matrix.java }}
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Echo JAVA version
        run: java --version
      - name: Cache SonarCloud packages
        uses: actions/cache@v3.0.7
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v3.0.7
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Echo Gradle version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --version
      - name: Execute clean
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --info --stacktrace clean
      - name: Execute check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --info --stacktrace check
      - name: Execute build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --info --stacktrace build
      - name: Sonarcube analyze
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          arguments: --info --stacktrace sonarqube
      - name: Upload reports as an artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reports-jdk${{ matrix.java }}-${{ matrix.os }}
          path: build/reports
          retention-days: 2
      - name: Upload test results as an artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: junit-results
          path: build/test-results
          retention-days: 1
      - name: Prepare spock reports artifact
        run: |
          mkdir -p build/gh-pages
          cp build/reports/spock/* build/gh-pages
          cp docs/gh-pages/* build/gh-pages
      - name: Upload spock reports as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: gh-pages
          path: build/gh-pages
          retention-days: 1

  publish-spock-reports:
    runs-on: ubuntu-latest
    name: Publish Spock Reports
    needs: build
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: gh-pages
          path: gh-pages-artifact
      - name: Get cached gems
        uses: actions/cache@v3.0.7
        with:
          path: gh-pages-artifact
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - name: Copy docs
        run: |
          ls -lha .
          ls -lha gh-pages-artifact
          sudo apt update
          sudo apt install bundler
          cd gh-pages-artifact
          bundle update
          bundle exec github-pages build
          touch _site/.nojekyll
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages-artifact/_site
          enable_jekyll: false

  publish-test-results:
    runs-on: ubuntu-latest
    name: Publish Unit Tests Results
    needs: build
    if: always()
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: junit-results
          path: junit-artifact
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          files: junit-artifact/**/*.xml
